### ISSUE TITLE
Registration of device using any of UDID from Wiki are not accepted by Apple

### ISSUE THREAD

**Issue by kopax-polyconseil** [futureware-tech/simulator-action#276]
**Describe the bug**

I would like to add a UDID to my list of allowed device, I use the `macos-11` image, `iPhone 13` `15.2` and Apple refuse it.

**To Reproduce**

Try to add the following UDID:

![image](https://user-images.githubusercontent.com/77674046/201911330-e2ed21cf-67e6-4d35-a887-90f814c92a98.png)

**Expected behavior**

I expect to be allowed to add the UDID 

**Screenshots**

```bash
[09:18:57]: {
  "errors" : [ {
    "id" : "bd128dfa-51f2-48d4-a737-10af5aae9743",
    "status" : "409",
    "code" : "ENTITY_ERROR.ATTRIBUTE.INVALID",
    "title" : "An attribute in the provided entity has invalid value",
    "resultCode" : 35,
    "detail" : "An invalid value '11DE7AF9-E77A-44F2-BECE-D8F9F69766B2' was provided for the parameter 'udid'."
  } ]
}
``` 

**Smartphone (If applicable):**
 - Device: iPhone 13
 - OS: 15.2
 - Browser NA
 - Version NA

**Comment by kopax-polyconseil** [comment]
I further checked and any of the existing simulator UDID are not accepted by apple:

![image](https://user-images.githubusercontent.com/77674046/201913376-14553163-52b8-42ff-927b-26ac888c3366.png)

**Comment by dotdoom** [comment]
Interesting, I haven't tried to use those Simulator UDIDs to register with Apple.  Those IDs are volatile, they are only valid for GitHub Runners (i.e. they may not be valid for your own hosted runners) and will change every time GitHub Actions team updates the machines where Actions are executed.

When you are talking about the list of allowed devices, what feature are you trying to allow?  So that I can reproduce.

**Comment by kopax-polyconseil** [comment]
1. We do not use self hosted runners.
1. We use a fixed version of `macos-11`
2. I try to register a device for my application, otherwise, we can't install signed `.ipa` on those devices.

**Comment by dotdoom** [comment]
While `macos-11` is indeed a fixed identifier, it's not a complete snapshot identifier (and GitHub Actions don't allow for a more granular version choice).  So within that version `11`, updates will affect Simulator UDIDs.  Currently, an update happens roughly every week (see https://github.com/futureware-tech/simulator-action/wiki/Devices-macos-11/_history).

Installing an `.ipa` on a Simulator is a rather rare activity; `.ipa` are normally built and signed for mobile devices (running `arm`), and Simulator is not an emulator -- an `.ipa` has to be built specifically for the architecture of the host machine (`x86_64` [at GitHub](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)), and usually the `.ipa` step is skipped when using XCode.

I'm not trying to suggest you a different approach yet, but to understand your case to reproduce it.  Few questions that should help me:

1. Are you following a specific guide to install `.ipa` on a Simulator?
2. Where do you obtain the `.ipa`?
3. Which steps do you follow to "register a device for your application"?
4. Have you tried to install the `.ipa` on a Simulator in your own test environment?

**Comment by kopax-polyconseil** [comment]
> 1. Are you following a specific guide to install .ipa on a Simulator?

No, no guide specific, I tried to extract the archive, drag an drop, and research showed me this is probably not possible or possible with hacky solution

> Where do you obtain the .ipa?

Appcenter

> Which steps do you follow to "register a device for your application"?

Check here: https://developer.apple.com/account/resources/devices/add

> Have you tried to install the .ipa on a Simulator in your own test environment?

Yes I did, not with success.

So far we have to run the iOS test after building the app in each CI, it takes roughly 1 hour just to run e2e testing, see here https://github.com/pass-culture/pass-culture-app-native/pull/3876

**Comment by dotdoom** [comment]
I see unofficial evidence on the Internet that running an `.ipa` downloaded from Appcenter is not achievable.  The problem seems to be that Appcenter does not accept `.ipa` built for Simulator (i.e. a host machine architecture rather than mobile).  See [1], [2].

You could probably build the [`.app` **for Simulator**](https://stackoverflow.com/questions/1984727/how-to-get-app-file-of-a-xcode-application) once and then distribute it to all CIs by means different than Appcenter (e.g. via Dropbox or GitHub Releases).  That would allow to save computing resources of multiple CIs building the same binary.

If you manage to obtain an `.ipa` from Appcenter which you can then successfully install to your local Simulator, we could look further into it to make it work on GitHub Actions as well.  Until then I'm unfortunately unable to help you as I am not familiar with Appcenter ecosystem.

[1]: https://medium.com/@laurent.sigal/building-for-ios-simulator-with-app-center-5e81b8954ca2
[2]: https://stackoverflow.com/questions/57730394/is-it-possible-to-build-and-distribute-simulator-builds-in-appcenter#comment106589094_57854096
